### ISSUE TITLE
Enhancement Request: Confirmation dialog when clicking "reset all stats"

### ISSUE THREAD

**Issue by vcuncg** [whitesoup12/remote-falcon-plugin#18]
This is LOW priority, but I was curious if there was any way you can add a confirmation dialog to the "reset all stats" button on the dashboard?  My fat finger clicking has caused me to accidentally clear the stats.  Would be nice to have a confirmation dialog so that it helps those with a tendency for user error issues like me :)

**Comment by whitesoup12** [comment]
I've added it to the list. This is minimal enough I could probably get it in pretty quick.

**Comment by whitesoup12** [comment]
This is completed.
