### ISSUE TITLE
Feature Request - Statistics Dashboard

### ISSUE THREAD

**Issue by cathelest** [whitesoup12/remote-falcon-plugin#5]
Would love to have a statistics Dashboard to see unique visitors, how many votes they cast etc, aswell as playlist stats etc,

**Comment by whitesoup12** [comment]
Added to my to-do list.

**Comment by cathelest** [comment]
Nice work with stats looks awesome, is there a way we can clear them at all?

**Comment by whitesoup12** [comment]
Currently in the works. :)
