### ISSUE TITLE
Add feature to play as overlay effect

### ISSUE THREAD

**Issue by Randomaker** [whitesoup12/remote-falcon-plugin#66]
Hello! I use Remote Falcon on xSchedule to allow user control of a snow machine.  Keith added a feature for me on the xSchedule plugin that lets you play the sequence selected from Remote Falcon as an overlay effect, so you can easily use it to control only specific elements of the show, such as my snow machine, while the rest of the show keeps going. He also needed to add a second checkbox to return this effect to RF instead of the normal sequence, that way RF doesn't allow the same sequence/overlay to restart while it is playing.

I would like to switch over to FPP from xSchedule, so I was wondering if this is something you would be interested in adding to this plugin as well. I know this is a bit of a specific request, so I understand if it doesn't happen, but it could definitely be useful for others as well.

Thanks a lot!

**Comment by whitesoup12** [comment]
On FPP you can add a Command to your remote playlist and trigger it from RF. So you could have a command to trigger the snow machine.

**Comment by Randomaker** [comment]
Ok, that makes sense. I'll give that a try. Thanks!

**Comment by Randomaker** [comment]
Wait wouldn't that let someone keep pressing the button while it is running? Is there some way to add a cooldown time?

**Comment by whitesoup12** [comment]
Not sure specifically how you would do it, but you could probably make a script to trigger the machine and wait a certain time before allowing it again.

**Comment by Randomaker** [comment]
I'm having trouble getting scripts to run from RF. If I add a script to my playlist set up in RF, it just doesn't show up in the RF control panel. Any ideas?

**Comment by whitesoup12** [comment]
Sorry, it's kind of unclear when syncing scripts to RF. Make sure you add a note to the playlist entry. The note is what the RF plugin uses as the name when it syncs.

**Comment by Randomaker** [comment]
Still not working. That works for FPP commands, but the script still isn't showing up.

**Comment by whitesoup12** [comment]
You need to create a command entry in the playlist that runs the script. You can't just sync the script itself to RF.
